In [1]:
import pandas as pd
import mysql.connector

In [2]:
data_parte1 = pd.read_csv("data_parte1.csv")
data_parte1

,Cédula,Nombre,Apellido,Dirección
0,1102792827,Rachel,Coleman,"5757 Thompson Overpass\nClarkmouth, FL 20893"
1,1102792828,John,Burns,"404 Renee Wall Apt. 092\nNew Joshua, PA 85625"
2,1102792829,Douglas,Ortega,"819 Ward Plains\nEast Monica, KY 81125"
3,1102792830,Diana,Bradley,"0962 Amanda Crest\nSouth Abigail, VA 50910"
4,1102792831,Chad,Atkins,"7960 Katherine Ferry Apt. 849\nLake Lisa, WY 1..."
...,...,...,...,...
995,1102793822,Steven,Logan,"79330 Thomas Knoll Suite 948\nTraviston, MA 71614"
996,1102793823,Marcia,Wells,38579 Nicholas Motorway Apt. 735\nLake Janiceb...
997,1102793824,John,Reilly,"4828 Coleman Lake Apt. 727\nCindyton, NY 58441"
998,1102793825,Kenneth,Roberts,"6532 Wood Junction\nNew Cindymouth, WY 53551"
999,1102793826,Ronnie,Schaefer,"7231 Miller Road\nPort William, AK 78565"

In [3]:
conexion=mysql.connector.connect(user='root', password='26061998santiago', host='localhost', database='datasets', port='3306')
print(conexion)

<mysql.connector.connection_cext.CMySQLConnection object at 0x00000212E0E21120>

In [4]:
cursor=conexion.cursor()

In [5]:
sql="""SELECT * FROM data_parte2"""
cursor.execute(sql)

In [6]:
columnas=cursor.column_names
columnas

('Cédula', 'Correo electrónico', 'Fecha de nacimiento')

In [7]:
conjunto_datos=cursor.fetchall()
conjunto_datos

[(1102792827, 'thomas35@example.com', datetime.date(1979, 10, 19)),
 (1102792828, 'lopezmichael@example.com', datetime.date(2007, 2, 21)),
 (1102792829, 'parkerpeter@example.org', datetime.date(1971, 10, 27)),
 (1102792830, 'patricia76@example.net', datetime.date(2018, 11, 25)),
 (1102792831, 'unelson@example.com', datetime.date(1924, 12, 22)),
 (1102792832, 'mjackson@example.com', datetime.date(1983, 11, 20)),
 (1102792833, 'idawson@example.net', datetime.date(1943, 9, 12)),
 (1102792834, 'thomasbrown@example.net', datetime.date(1990, 2, 11)),
 (1102792835, 'sallison@example.com', datetime.date(1998, 12, 3)),
 (1102792836, 'laurie33@example.net', datetime.date(1948, 7, 21)),
 (1102792837, 'tonyaharris@example.com', datetime.date(2018, 12, 29)),
 (1102792838, 'manuelwilliams@example.org', datetime.date(1940, 6, 1)),
 (1102792839, 'ndavis@example.com', datetime.date(1938, 9, 22)),
 (1102792840, 'michael96@example.com', datetime.date(1985, 7, 20)),
 (1102792841, 'espinozakelly@example.net', datetime.date(2023, 10, 23)),
 (1102792842, 'cummingscarlos@example.net', datetime.date(1970, 4, 8)),
 (1102792843, 'halvarez@example.org', datetime.date(1958, 12, 30)),
 (1102792844, 'wpace@example.net', datetime.date(2013, 12, 24)),
 (1102792845, 'twilliams@example.com', datetime.date(2012, 10, 24)),
 (1102792846, 'nicholaspaul@example.com', datetime.date(1999, 9, 27)),
 (1102792847, 'beckjames@example.net', datetime.date(1934, 3, 23)),
 (1102792848, 'wendy95@example.com', datetime.date(1980, 12, 16)),
 (1102792849, 'ryancooper@example.org', datetime.date(2008, 6, 7)),
 (1102792850, 'pcastro@example.com', datetime.date(1956, 2, 20)),
 (1102792851, 'linda20@example.com', datetime.date(1970, 12, 18)),
 (1102792852, 'rgibson@example.org', datetime.date(1925, 4, 23)),
 (1102792853, 'dan89@example.org', datetime.date(1912, 10, 10)),
 (1102792854, 'fhammond@example.com', datetime.date(1980, 10, 11)),
 (1102792855, 'brandiwilson@example.com', datetime.date(2019, 9, 30)),
 (1102792856, 'wwilliams@example.com', datetime.date(2015, 5, 11)),
 (1102792857, 'ugomez@example.net', datetime.date(1914, 5, 2)),
 (1102792858, 'moorebrian@example.net', datetime.date(2000, 5, 22)),
 (1102792859, 'adambaker@example.com', datetime.date(2016, 2, 22)),
 (1102792860, 'ajones@example.org', datetime.date(1981, 3, 9)),
 (1102792861, 'nbaker@example.net', datetime.date(1933, 6, 22)),
 (1102792862, 'jonathan27@example.net', datetime.date(1944, 10, 8)),
 (1102792863, 'molinabrian@example.com', datetime.date(1990, 11, 2)),
 (1102792864, 'carolynwalker@example.net', datetime.date(1956, 3, 25)),
 (1102792865, 'brittany63@example.org', datetime.date(1915, 3, 24)),
 (1102792866, 'katrina52@example.com', datetime.date(1980, 6, 25)),
 (1102792867, 'afernandez@example.com', datetime.date(2016, 6, 14)),
 (1102792868, 'danathomas@example.net', datetime.date(1930, 2, 11)),
 (1102792869, 'ambercampbell@example.org', datetime.date(1957, 7, 12)),
 (1102792870, 'stuartdickerson@example.com', datetime.date(1975, 3, 19)),
 (1102792871, 'nicholas02@example.net', datetime.date(2009, 2, 13)),
 (1102792872, 'kpruitt@example.net', datetime.date(1931, 11, 29)),
 (1102792873, 'fieldslydia@example.com', datetime.date(2019, 6, 22)),
 (1102792874, 'markjenkins@example.org', datetime.date(2020, 8, 5)),
 (1102792875, 'allen64@example.org', datetime.date(1935, 10, 31)),
 (1102792876, 'phoward@example.net', datetime.date(1978, 5, 17)),
 (1102792877, 'blake96@example.net', datetime.date(1948, 8, 4)),
 (1102792878, 'patrick84@example.com', datetime.date(1917, 10, 23)),
 (1102792879, 'shannon10@example.com', datetime.date(1946, 8, 3)),
 (1102792880, 'andrea55@example.org', datetime.date(1930, 5, 24)),
 (1102792881, 'mark05@example.net', datetime.date(1985, 4, 22)),
 (1102792882, 'ashleywalton@example.net', datetime.date(2006, 10, 8)),
 (1102792883, 'qmoore@example.com', datetime.date(1960, 7, 13)),
 (1102792884, 'rdaniel@example.net', datetime.date(1962, 1, 12)),
 (1102792885, 'vwalker@example.com', datetime.date(1969, 8, 29)),
 (1102792886, 'jonathan51@example.org', datetime.date(1948, 7, 19)),
 (1102792887, 'cwells@example.org', datetime.date(1929, 4, 2)),
 (1102792888, 'morgan35@example.net', datetime.date(1941, 4, 8)),
 (1102792889, 'jacob92@example.net', datetime.date(1929, 7, 8)),
 (1102792890, 'kathleen14@example.org', datetime.date(1994, 7, 6)),
 (1102792891, 'francisco67@example.com', datetime.date(2024, 3, 17)),
 (1102792892, 'brownlisa@example.net', datetime.date(1917, 10, 27)),
 (1102792893, 'vsilva@example.org', datetime.date(1977, 2, 19)),
 (1102792894, 'martinezkatherine@example.com', datetime.date(1909, 3, 28)),
 (1102792895, 'danielle91@example.org', datetime.date(1922, 10, 6)),
 (1102792896, 'istewart@example.com', datetime.date(1977, 2, 17)),
 (1102792897, 'kayla03@example.org', datetime.date(1974, 5, 28)),
 (1102792898, 'jonathanhayes@example.org', datetime.date(1970, 4, 14)),
 (1102792899, 'dholland@example.net', datetime.date(1916, 4, 24)),
 (1102792900, 'zdouglas@example.net', datetime.date(1916, 6, 22)),
 (1102792901, 'zanderson@example.org', datetime.date(1966, 3, 15)),
 (1102792902, 'karenbutler@example.org', datetime.date(1935, 4, 28)),
 (1102792903, 'lindsay70@example.com', datetime.date(1933, 2, 1)),
 (1102792904, 'zguerrero@example.com', datetime.date(2005, 10, 17)),
 (1102792905, 'nicole60@example.net', datetime.date(1929, 8, 6)),
 (1102792906, 'nathanielchristensen@example.net', datetime.date(1969, 9, 3)),
 (1102792907, 'lwilliams@example.com', datetime.date(2000, 3, 15)),
 (1102792908, 'joshuawebster@example.net', datetime.date(1971, 12, 22)),
 (1102792909, 'johnchapman@example.org', datetime.date(1952, 12, 22)),
 (1102792910, 'johnsonrichard@example.com', datetime.date(1985, 2, 15)),
 (1102792911, 'jeremysparks@example.net', datetime.date(1934, 4, 12)),
 (1102792912, 'valdezjessica@example.net', datetime.date(1945, 3, 1)),
 (1102792913, 'tammy49@example.com', datetime.date(1911, 6, 28)),
 (1102792914, 'sarah11@example.net', datetime.date(1990, 2, 26)),
 (1102792915, 'samantharose@example.org', datetime.date(1999, 9, 27)),
 (1102792916, 'housephillip@example.net', datetime.date(2011, 11, 23)),
 (1102792917, 'timothy55@example.com', datetime.date(2000, 2, 11)),
 (1102792918, 'christopher25@example.com', datetime.date(1915, 1, 24)),
 (1102792919, 'hsmith@example.com', datetime.date(1922, 5, 23)),
 (1102792920, 'brentjefferson@example.org', datetime.date(1933, 6, 14)),
 (1102792921, 'jacksonpeter@example.com', datetime.date(2024, 3, 22)),
 (1102792922, 'taylorrobertson@example.net', datetime.date(1938, 9, 22)),
 (1102792923, 'pholland@example.org', datetime.date(2012, 5, 8)),
 (1102792924, 'leslie29@example.com', datetime.date(2022, 10, 12)),
 (1102792925, 'prattwendy@example.org', datetime.date(1922, 9, 22)),
 (1102792926, 'jacquelineroberts@example.org', datetime.date(1916, 5, 10)),
 (1102792927, 'alfred53@example.com', datetime.date(1983, 7, 26)),
 (1102792928, 'gillespiejames@example.net', datetime.date(1985, 4, 9)),
 (1102792929, 'stephaniebrown@example.org', datetime.date(1948, 3, 11)),
 (1102792930, 'joel54@example.net', datetime.date(1909, 9, 17)),
 (1102792931, 'elizabeth98@example.com', datetime.date(1910, 5, 7)),
 (1102792932, 'jamesschmidt@example.net', datetime.date(1944, 12, 5)),
 (1102792933, 'tamifrank@example.net', datetime.date(1953, 10, 11)),
 (1102792934, 'fordjessica@example.net', datetime.date(1963, 1, 28)),
 (1102792935, 'juan22@example.net', datetime.date(1944, 11, 27)),
 (1102792936, 'blackemily@example.net', datetime.date(2007, 11, 13)),
 (1102792937, 'baldwinbrian@example.com', datetime.date(1942, 2, 7)),
 (1102792938, 'teresablackwell@example.net', datetime.date(1965, 7, 1)),
 (1102792939, 'willie11@example.org', datetime.date(1910, 11, 14)),
 (1102792940, 'hgarcia@example.net', datetime.date(1970, 9, 27)),
 (1102792941, 'kbartlett@example.net', datetime.date(1921, 8, 9)),
 (1102792942, 'danieldickson@example.org', datetime.date(1913, 1, 23)),
 (1102792943, 'amyadams@example.com', datetime.date(1954, 3, 16)),
 (1102792944, 'lisalove@example.org', datetime.date(1961, 2, 5)),
 (1102792945, 'garciagrant@example.org', datetime.date(1915, 4, 30)),
 (1102792946, 'nflores@example.com', datetime.date(1971, 7, 13)),
 (1102792947, 'lauren43@example.com', datetime.date(1915, 11, 7)),
 (1102792948, 'sarah03@example.net', datetime.date(1994, 2, 10)),
 (1102792949, 'nicholas07@example.net', datetime.date(1955, 10, 12)),
 (1102792950, 'jared27@example.net', datetime.date(1961, 11, 9)),
 (1102792951, 'littledanielle@example.net', datetime.date(1970, 1, 14)),
 (1102792952, 'jennifergarcia@example.org', datetime.date(1934, 10, 22)),
 (1102792953, 'ahancock@example.net', datetime.date(1969, 4, 20)),
 (1102792954, 'kennedymarissa@example.com', datetime.date(1951, 2, 8)),
 (1102792955, 'sfarmer@example.net', datetime.date(1983, 7, 31)),
 (1102792956, 'ayalazachary@example.net', datetime.date(1976, 10, 17)),
 (1102792957, 'mccormicknicholas@example.org', datetime.date(1920, 6, 4)),
 (1102792958, 'guzmanana@example.net', datetime.date(1908, 8, 22)),
 (1102792959, 'katrinawheeler@example.net', datetime.date(1923, 3, 3)),
 (1102792960, 'millerchristina@example.com', datetime.date(1956, 6, 14)),
 (1102792961, 'sethmosley@example.com', datetime.date(1953, 7, 18)),
 (1102792962, 'melissa96@example.org', datetime.date(2010, 8, 12)),
 (1102792963, 'brandymaldonado@example.com', datetime.date(1976, 10, 28)),
 (1102792964, 'stevenduarte@example.org', datetime.date(1948, 6, 7)),
 (1102792965, 'sean05@example.net', datetime.date(1922, 3, 3)),
 (1102792966, 'garciadennis@example.com', datetime.date(1934, 2, 12)),
 (1102792967, 'barbararobinson@example.net', datetime.date(1969, 10, 7)),
 (1102792968, 'blankenshipanthony@example.net', datetime.date(2006, 1, 28)),
 (1102792969, 'traci28@example.com', datetime.date(1925, 6, 21)),
 (1102792970, 'mosesmegan@example.net', datetime.date(1989, 6, 5)),
 (1102792971, 'llucas@example.org', datetime.date(1911, 1, 23)),
 (1102792972, 'marshallchad@example.com', datetime.date(1940, 4, 19)),
 (1102792973, 'terrylinda@example.net', datetime.date(1992, 5, 10)),
 (1102792974, 'patkins@example.com', datetime.date(1911, 1, 29)),
 (1102792975, 'kevinpruitt@example.org', datetime.date(1969, 6, 28)),
 (1102792976, 'kathy95@example.org', datetime.date(2017, 10, 21)),
 (1102792977, 'antonio29@example.org', datetime.date(2019, 12, 30)),
 (1102792978, 'fwright@example.net', datetime.date(1923, 11, 23)),
 (1102792979, 'travis15@example.org', datetime.date(1990, 3, 22)),
 (1102792980, 'ericsimmons@example.org', datetime.date(1966, 4, 1)),
 (1102792981, 'williamssean@example.net', datetime.date(1957, 2, 26)),
 (1102792982, 'parkerearl@example.com', datetime.date(1955, 7, 26)),
 (1102792983, 'meganfloyd@example.org', datetime.date(2023, 3, 31)),
 (1102792984, 'barnettjoseph@example.org', datetime.date(2014, 12, 10)),
 (1102792985, 'malik35@example.net', datetime.date(1919, 7, 21)),
 (1102792986, 'yward@example.org', datetime.date(1938, 8, 18)),
 (1102792987, 'jhart@example.com', datetime.date(1952, 2, 8)),
 (1102792988, 'nstewart@example.com', datetime.date(1978, 10, 6)),
 (1102792989, 'hunter76@example.net', datetime.date(1957, 12, 20)),
 (1102792990, 'diana54@example.com', datetime.date(2023, 4, 4)),
 (1102792991, 'scottbrowning@example.org', datetime.date(2016, 11, 24)),
 (1102792992, 'alexander18@example.net', datetime.date(1955, 5, 12)),
 (1102792993, 'benjamingonzalez@example.com', datetime.date(1912, 7, 13)),
 (1102792994, 'johnsonjenna@example.org', datetime.date(1977, 3, 1)),
 (1102792995, 'hshah@example.org', datetime.date(1956, 10, 29)),
 (1102792996, 'carterkevin@example.com', datetime.date(1979, 12, 28)),
 (1102792997, 'michaelbaker@example.net', datetime.date(1910, 9, 11)),
 (1102792998, 'phyllisayers@example.com', datetime.date(1964, 6, 7)),
 (1102792999, 'keithcarter@example.org', datetime.date(1934, 5, 13)),
 (1102793000, 'ibowen@example.net', datetime.date(2003, 3, 20)),
 (1102793001, 'ucruz@example.com', datetime.date(2001, 9, 21)),
 (1102793002, 'landerson@example.org', datetime.date(1941, 10, 16)),
 (1102793003, 'jesusbailey@example.net', datetime.date(1983, 8, 12)),
 (1102793004, 'vanessalarson@example.com', datetime.date(1975, 8, 5)),
 (1102793005, 'marc33@example.org', datetime.date(1965, 11, 24)),
 (1102793006, 'rroberts@example.org', datetime.date(1960, 8, 25)),
 (1102793007, 'wjackson@example.org', datetime.date(1934, 10, 18)),
 (1102793008, 'gfernandez@example.net', datetime.date(1942, 12, 31)),
 (1102793009, 'marcia02@example.com', datetime.date(1968, 2, 26)),
 (1102793010, 'kmedina@example.com', datetime.date(1937, 6, 8)),
 (1102793011, 'hwells@example.org', datetime.date(2010, 1, 12)),
 (1102793012, 'pfarrell@example.net', datetime.date(2002, 11, 24)),
 (1102793013, 'hollandrandy@example.org', datetime.date(2011, 7, 16)),
 (1102793014, 'zharrison@example.com', datetime.date(1965, 7, 2)),
 (1102793015, 'sowens@example.org', datetime.date(1988, 9, 15)),
 (1102793016, 'marysmith@example.net', datetime.date(1942, 1, 17)),
 (1102793017, 'wbrown@example.net', datetime.date(1977, 7, 20)),
 (1102793018, 'ramseytina@example.com', datetime.date(1935, 4, 16)),
 (1102793019, 'anthonydavid@example.com', datetime.date(1911, 2, 28)),
 (1102793020, 'xguzman@example.org', datetime.date(1998, 5, 3)),
 (1102793021, 'fisherscott@example.org', datetime.date(1977, 3, 1)),
 (1102793022, 'robinsonricky@example.net', datetime.date(1952, 6, 9)),
 (1102793023, 'cartervanessa@example.com', datetime.date(1998, 2, 18)),
 (1102793024, 'kimberly22@example.net', datetime.date(1925, 7, 12)),
 (1102793025, 'paula29@example.com', datetime.date(1967, 10, 17)),
 (1102793026, 'heather45@example.com', datetime.date(1957, 4, 23)),
 (1102793027, 'nrhodes@example.com', datetime.date(1927, 7, 6)),
 (1102793028, 'ashley55@example.org', datetime.date(2018, 11, 20)),
 (1102793029, 'janetfitzgerald@example.org', datetime.date(1920, 10, 19)),
 (1102793030, 'alanbowers@example.net', datetime.date(1979, 10, 3)),
 (1102793031, 'tylertran@example.org', datetime.date(1995, 1, 22)),
 (1102793032, 'julie19@example.com', datetime.date(1923, 3, 27)),
 (1102793033, 'stevenlong@example.net', datetime.date(1933, 7, 4)),
 (1102793034, 'connie98@example.com', datetime.date(1967, 5, 31)),
 (1102793035, 'websterjose@example.org', datetime.date(2006, 5, 19)),
 (1102793036, 'ccook@example.org', datetime.date(2003, 10, 26)),
 (1102793037, 'jessica72@example.com', datetime.date(2020, 10, 6)),
 (1102793038, 'davidperez@example.net', datetime.date(1953, 6, 4)),
 (1102793039, 'hartcaitlin@example.com', datetime.date(1965, 5, 20)),
 (1102793040, 'vgarcia@example.net', datetime.date(1944, 1, 26)),
 (1102793041, 'benjamingardner@example.org', datetime.date(1955, 8, 9)),
 (1102793042, 'kayla36@example.com', datetime.date(1962, 6, 13)),
 (1102793043, 'jamesfriedman@example.org', datetime.date(1963, 1, 25)),
 (1102793044, 'melissalam@example.com', datetime.date(1961, 2, 20)),
 (1102793045, 'anthony75@example.com', datetime.date(1977, 2, 10)),
 (1102793046, 'mtanner@example.com', datetime.date(1948, 8, 6)),
 (1102793047, 'ygarcia@example.com', datetime.date(1995, 7, 4)),
 (1102793048, 'kimberly66@example.org', datetime.date(1940, 4, 25)),
 (1102793049, 'lhouston@example.org', datetime.date(1965, 1, 29)),
 (1102793050, 'brandon03@example.org', datetime.date(2005, 8, 14)),
 (1102793051, 'fhines@example.org', datetime.date(2003, 5, 24)),
 (1102793052, 'brendabaker@example.com', datetime.date(1978, 2, 6)),
 (1102793053, 'wellsbrandon@example.com', datetime.date(1984, 9, 13)),
 (1102793054, 'davidnguyen@example.com', datetime.date(1963, 8, 12)),
 (1102793055, 'rebeccamaldonado@example.com', datetime.date(2008, 1, 13)),
 (1102793056, 'kristen85@example.net', datetime.date(1913, 8, 12)),
 (1102793057, 'shawntaylor@example.org', datetime.date(1920, 7, 26)),
 (1102793058, 'jmarshall@example.org', datetime.date(2023, 7, 25)),
 (1102793059, 'debrajackson@example.net', datetime.date(1968, 11, 2)),
 (1102793060, 'shannon87@example.net', datetime.date(1983, 4, 24)),
 (1102793061, 'carrillodustin@example.org', datetime.date(2019, 3, 8)),
 (1102793062, 'rponce@example.org', datetime.date(1939, 11, 27)),
 (1102793063, 'timothy86@example.org', datetime.date(2009, 2, 1)),
 (1102793064, 'andrewyoung@example.org', datetime.date(1980, 2, 14)),
 (1102793065, 'rangelscott@example.com', datetime.date(1931, 4, 13)),
 (1102793066, 'lucas31@example.org', datetime.date(1962, 7, 17)),
 (1102793067, 'vgreer@example.org', datetime.date(1990, 9, 20)),
 (1102793068, 'cwebster@example.net', datetime.date(1979, 8, 27)),
 (1102793069, 'zhowell@example.org', datetime.date(1989, 12, 6)),
 (1102793070, 'vazqueztiffany@example.org', datetime.date(1926, 4, 2)),
 (1102793071, 'nlewis@example.net', datetime.date(1910, 11, 18)),
 (1102793072, 'awatts@example.org', datetime.date(1988, 6, 26)),
 (1102793073, 'claire10@example.com', datetime.date(1978, 12, 14)),
 (1102793074, 'pwilson@example.org', datetime.date(1999, 2, 17)),
 (1102793075, 'danaclark@example.org', datetime.date(1927, 1, 20)),
 (1102793076, 'ogonzalez@example.org', datetime.date(1951, 9, 8)),
 (1102793077, 'christopher88@example.com', datetime.date(1988, 9, 29)),
 (1102793078, 'nturner@example.org', datetime.date(1927, 7, 17)),
 (1102793079, 'alvarezheather@example.net', datetime.date(1908, 11, 24)),
 (1102793080, 'dmann@example.org', datetime.date(1984, 2, 26)),
 (1102793081, 'benjamin67@example.com', datetime.date(2013, 2, 10)),
 (1102793082, 'michael32@example.net', datetime.date(1926, 12, 9)),
 (1102793083, 'griffithjoshua@example.com', datetime.date(1992, 8, 6)),
 (1102793084, 'ian64@example.org', datetime.date(1957, 10, 6)),
 (1102793085, 'bullockbrandon@example.org', datetime.date(2002, 9, 1)),
 (1102793086, 'karenhebert@example.org', datetime.date(1980, 2, 29)),
 (1102793087, 'fdavis@example.com', datetime.date(1975, 11, 25)),
 (1102793088, 'kelsey84@example.net', datetime.date(1914, 9, 28)),
 (1102793089, 'kirkbrett@example.com', datetime.date(2022, 5, 3)),
 (1102793090, 'herreraderrick@example.com', datetime.date(1925, 11, 7)),
 (1102793091, 'haleycampbell@example.org', datetime.date(1994, 12, 18)),
 (1102793092, 'john34@example.com', datetime.date(1980, 7, 12)),
 (1102793093, 'nhill@example.net', datetime.date(2016, 5, 15)),
 (1102793094, 'victoria94@example.org', datetime.date(2010, 6, 10)),
 (1102793095, 'dprince@example.com', datetime.date(1964, 7, 19)),
 (1102793096, 'qgillespie@example.net', datetime.date(2012, 2, 12)),
 (1102793097, 'jacqueline00@example.com', datetime.date(1961, 12, 5)),
 (1102793098, 'theresahunt@example.com', datetime.date(1979, 9, 30)),
 (1102793099, 'andersonalyssa@example.com', datetime.date(1940, 6, 29)),
 (1102793100, 'ewatkins@example.net', datetime.date(1984, 1, 16)),
 (1102793101, 'carrilloheather@example.com', datetime.date(1943, 2, 4)),
 (1102793102, 'whudson@example.net', datetime.date(1922, 5, 4)),
 (1102793103, 'joseph55@example.net', datetime.date(1958, 10, 17)),
 (1102793104, 'mcarrillo@example.org', datetime.date(1950, 7, 22)),
 (1102793105, 'glennsullivan@example.org', datetime.date(1909, 11, 2)),
 (1102793106, 'elizabethavery@example.net', datetime.date(1996, 10, 25)),
 (1102793107, 'jason60@example.com', datetime.date(2020, 1, 22)),
 (1102793108, 'elainesutton@example.net', datetime.date(1941, 7, 29)),
 (1102793109, 'carol93@example.com', datetime.date(1997, 4, 26)),
 (1102793110, 'carlapatterson@example.com', datetime.date(2013, 2, 14)),
 (1102793111, 'zachary61@example.com', datetime.date(1946, 5, 20)),
 (1102793112, 'joneselizabeth@example.com', datetime.date(1929, 1, 24)),
 (1102793113, 'victoriarojas@example.net', datetime.date(1957, 9, 19)),
 (1102793114, 'mlynch@example.com', datetime.date(1992, 1, 3)),
 (1102793115, 'eosborn@example.org', datetime.date(1976, 9, 11)),
 (1102793116, 'ejohnson@example.net', datetime.date(1914, 5, 6)),
 (1102793117, 'seangallagher@example.org', datetime.date(1991, 1, 8)),

In [8]:
lista_conjunto_datos=[]
for fila in conjunto_datos:
    lista_conjunto_datos.append(list(fila))
lista_conjunto_datos

[[1102792827, 'thomas35@example.com', datetime.date(1979, 10, 19)],
 [1102792828, 'lopezmichael@example.com', datetime.date(2007, 2, 21)],
 [1102792829, 'parkerpeter@example.org', datetime.date(1971, 10, 27)],
 [1102792830, 'patricia76@example.net', datetime.date(2018, 11, 25)],
 [1102792831, 'unelson@example.com', datetime.date(1924, 12, 22)],
 [1102792832, 'mjackson@example.com', datetime.date(1983, 11, 20)],
 [1102792833, 'idawson@example.net', datetime.date(1943, 9, 12)],
 [1102792834, 'thomasbrown@example.net', datetime.date(1990, 2, 11)],
 [1102792835, 'sallison@example.com', datetime.date(1998, 12, 3)],
 [1102792836, 'laurie33@example.net', datetime.date(1948, 7, 21)],
 [1102792837, 'tonyaharris@example.com', datetime.date(2018, 12, 29)],
 [1102792838, 'manuelwilliams@example.org', datetime.date(1940, 6, 1)],
 [1102792839, 'ndavis@example.com', datetime.date(1938, 9, 22)],
 [1102792840, 'michael96@example.com', datetime.date(1985, 7, 20)],
 [1102792841, 'espinozakelly@example.net', datetime.date(2023, 10, 23)],
 [1102792842, 'cummingscarlos@example.net', datetime.date(1970, 4, 8)],
 [1102792843, 'halvarez@example.org', datetime.date(1958, 12, 30)],
 [1102792844, 'wpace@example.net', datetime.date(2013, 12, 24)],
 [1102792845, 'twilliams@example.com', datetime.date(2012, 10, 24)],
 [1102792846, 'nicholaspaul@example.com', datetime.date(1999, 9, 27)],
 [1102792847, 'beckjames@example.net', datetime.date(1934, 3, 23)],
 [1102792848, 'wendy95@example.com', datetime.date(1980, 12, 16)],
 [1102792849, 'ryancooper@example.org', datetime.date(2008, 6, 7)],
 [1102792850, 'pcastro@example.com', datetime.date(1956, 2, 20)],
 [1102792851, 'linda20@example.com', datetime.date(1970, 12, 18)],
 [1102792852, 'rgibson@example.org', datetime.date(1925, 4, 23)],
 [1102792853, 'dan89@example.org', datetime.date(1912, 10, 10)],
 [1102792854, 'fhammond@example.com', datetime.date(1980, 10, 11)],
 [1102792855, 'brandiwilson@example.com', datetime.date(2019, 9, 30)],
 [1102792856, 'wwilliams@example.com', datetime.date(2015, 5, 11)],
 [1102792857, 'ugomez@example.net', datetime.date(1914, 5, 2)],
 [1102792858, 'moorebrian@example.net', datetime.date(2000, 5, 22)],
 [1102792859, 'adambaker@example.com', datetime.date(2016, 2, 22)],
 [1102792860, 'ajones@example.org', datetime.date(1981, 3, 9)],
 [1102792861, 'nbaker@example.net', datetime.date(1933, 6, 22)],
 [1102792862, 'jonathan27@example.net', datetime.date(1944, 10, 8)],
 [1102792863, 'molinabrian@example.com', datetime.date(1990, 11, 2)],
 [1102792864, 'carolynwalker@example.net', datetime.date(1956, 3, 25)],
 [1102792865, 'brittany63@example.org', datetime.date(1915, 3, 24)],
 [1102792866, 'katrina52@example.com', datetime.date(1980, 6, 25)],
 [1102792867, 'afernandez@example.com', datetime.date(2016, 6, 14)],
 [1102792868, 'danathomas@example.net', datetime.date(1930, 2, 11)],
 [1102792869, 'ambercampbell@example.org', datetime.date(1957, 7, 12)],
 [1102792870, 'stuartdickerson@example.com', datetime.date(1975, 3, 19)],
 [1102792871, 'nicholas02@example.net', datetime.date(2009, 2, 13)],
 [1102792872, 'kpruitt@example.net', datetime.date(1931, 11, 29)],
 [1102792873, 'fieldslydia@example.com', datetime.date(2019, 6, 22)],
 [1102792874, 'markjenkins@example.org', datetime.date(2020, 8, 5)],
 [1102792875, 'allen64@example.org', datetime.date(1935, 10, 31)],
 [1102792876, 'phoward@example.net', datetime.date(1978, 5, 17)],
 [1102792877, 'blake96@example.net', datetime.date(1948, 8, 4)],
 [1102792878, 'patrick84@example.com', datetime.date(1917, 10, 23)],
 [1102792879, 'shannon10@example.com', datetime.date(1946, 8, 3)],
 [1102792880, 'andrea55@example.org', datetime.date(1930, 5, 24)],
 [1102792881, 'mark05@example.net', datetime.date(1985, 4, 22)],
 [1102792882, 'ashleywalton@example.net', datetime.date(2006, 10, 8)],
 [1102792883, 'qmoore@example.com', datetime.date(1960, 7, 13)],
 [1102792884, 'rdaniel@example.net', datetime.date(1962, 1, 12)],
 [1102792885, 'vwalker@example.com', datetime.date(1969, 8, 29)],
 [1102792886, 'jonathan51@example.org', datetime.date(1948, 7, 19)],
 [1102792887, 'cwells@example.org', datetime.date(1929, 4, 2)],
 [1102792888, 'morgan35@example.net', datetime.date(1941, 4, 8)],
 [1102792889, 'jacob92@example.net', datetime.date(1929, 7, 8)],
 [1102792890, 'kathleen14@example.org', datetime.date(1994, 7, 6)],
 [1102792891, 'francisco67@example.com', datetime.date(2024, 3, 17)],
 [1102792892, 'brownlisa@example.net', datetime.date(1917, 10, 27)],
 [1102792893, 'vsilva@example.org', datetime.date(1977, 2, 19)],
 [1102792894, 'martinezkatherine@example.com', datetime.date(1909, 3, 28)],
 [1102792895, 'danielle91@example.org', datetime.date(1922, 10, 6)],
 [1102792896, 'istewart@example.com', datetime.date(1977, 2, 17)],
 [1102792897, 'kayla03@example.org', datetime.date(1974, 5, 28)],
 [1102792898, 'jonathanhayes@example.org', datetime.date(1970, 4, 14)],
 [1102792899, 'dholland@example.net', datetime.date(1916, 4, 24)],
 [1102792900, 'zdouglas@example.net', datetime.date(1916, 6, 22)],
 [1102792901, 'zanderson@example.org', datetime.date(1966, 3, 15)],
 [1102792902, 'karenbutler@example.org', datetime.date(1935, 4, 28)],
 [1102792903, 'lindsay70@example.com', datetime.date(1933, 2, 1)],
 [1102792904, 'zguerrero@example.com', datetime.date(2005, 10, 17)],
 [1102792905, 'nicole60@example.net', datetime.date(1929, 8, 6)],
 [1102792906, 'nathanielchristensen@example.net', datetime.date(1969, 9, 3)],
 [1102792907, 'lwilliams@example.com', datetime.date(2000, 3, 15)],
 [1102792908, 'joshuawebster@example.net', datetime.date(1971, 12, 22)],
 [1102792909, 'johnchapman@example.org', datetime.date(1952, 12, 22)],
 [1102792910, 'johnsonrichard@example.com', datetime.date(1985, 2, 15)],
 [1102792911, 'jeremysparks@example.net', datetime.date(1934, 4, 12)],
 [1102792912, 'valdezjessica@example.net', datetime.date(1945, 3, 1)],
 [1102792913, 'tammy49@example.com', datetime.date(1911, 6, 28)],
 [1102792914, 'sarah11@example.net', datetime.date(1990, 2, 26)],
 [1102792915, 'samantharose@example.org', datetime.date(1999, 9, 27)],
 [1102792916, 'housephillip@example.net', datetime.date(2011, 11, 23)],
 [1102792917, 'timothy55@example.com', datetime.date(2000, 2, 11)],
 [1102792918, 'christopher25@example.com', datetime.date(1915, 1, 24)],
 [1102792919, 'hsmith@example.com', datetime.date(1922, 5, 23)],
 [1102792920, 'brentjefferson@example.org', datetime.date(1933, 6, 14)],
 [1102792921, 'jacksonpeter@example.com', datetime.date(2024, 3, 22)],
 [1102792922, 'taylorrobertson@example.net', datetime.date(1938, 9, 22)],
 [1102792923, 'pholland@example.org', datetime.date(2012, 5, 8)],
 [1102792924, 'leslie29@example.com', datetime.date(2022, 10, 12)],
 [1102792925, 'prattwendy@example.org', datetime.date(1922, 9, 22)],
 [1102792926, 'jacquelineroberts@example.org', datetime.date(1916, 5, 10)],
 [1102792927, 'alfred53@example.com', datetime.date(1983, 7, 26)],
 [1102792928, 'gillespiejames@example.net', datetime.date(1985, 4, 9)],
 [1102792929, 'stephaniebrown@example.org', datetime.date(1948, 3, 11)],
 [1102792930, 'joel54@example.net', datetime.date(1909, 9, 17)],
 [1102792931, 'elizabeth98@example.com', datetime.date(1910, 5, 7)],
 [1102792932, 'jamesschmidt@example.net', datetime.date(1944, 12, 5)],
 [1102792933, 'tamifrank@example.net', datetime.date(1953, 10, 11)],
 [1102792934, 'fordjessica@example.net', datetime.date(1963, 1, 28)],
 [1102792935, 'juan22@example.net', datetime.date(1944, 11, 27)],
 [1102792936, 'blackemily@example.net', datetime.date(2007, 11, 13)],
 [1102792937, 'baldwinbrian@example.com', datetime.date(1942, 2, 7)],
 [1102792938, 'teresablackwell@example.net', datetime.date(1965, 7, 1)],
 [1102792939, 'willie11@example.org', datetime.date(1910, 11, 14)],
 [1102792940, 'hgarcia@example.net', datetime.date(1970, 9, 27)],
 [1102792941, 'kbartlett@example.net', datetime.date(1921, 8, 9)],
 [1102792942, 'danieldickson@example.org', datetime.date(1913, 1, 23)],
 [1102792943, 'amyadams@example.com', datetime.date(1954, 3, 16)],
 [1102792944, 'lisalove@example.org', datetime.date(1961, 2, 5)],
 [1102792945, 'garciagrant@example.org', datetime.date(1915, 4, 30)],
 [1102792946, 'nflores@example.com', datetime.date(1971, 7, 13)],
 [1102792947, 'lauren43@example.com', datetime.date(1915, 11, 7)],
 [1102792948, 'sarah03@example.net', datetime.date(1994, 2, 10)],
 [1102792949, 'nicholas07@example.net', datetime.date(1955, 10, 12)],
 [1102792950, 'jared27@example.net', datetime.date(1961, 11, 9)],
 [1102792951, 'littledanielle@example.net', datetime.date(1970, 1, 14)],
 [1102792952, 'jennifergarcia@example.org', datetime.date(1934, 10, 22)],
 [1102792953, 'ahancock@example.net', datetime.date(1969, 4, 20)],
 [1102792954, 'kennedymarissa@example.com', datetime.date(1951, 2, 8)],
 [1102792955, 'sfarmer@example.net', datetime.date(1983, 7, 31)],
 [1102792956, 'ayalazachary@example.net', datetime.date(1976, 10, 17)],
 [1102792957, 'mccormicknicholas@example.org', datetime.date(1920, 6, 4)],
 [1102792958, 'guzmanana@example.net', datetime.date(1908, 8, 22)],
 [1102792959, 'katrinawheeler@example.net', datetime.date(1923, 3, 3)],
 [1102792960, 'millerchristina@example.com', datetime.date(1956, 6, 14)],
 [1102792961, 'sethmosley@example.com', datetime.date(1953, 7, 18)],
 [1102792962, 'melissa96@example.org', datetime.date(2010, 8, 12)],
 [1102792963, 'brandymaldonado@example.com', datetime.date(1976, 10, 28)],
 [1102792964, 'stevenduarte@example.org', datetime.date(1948, 6, 7)],
 [1102792965, 'sean05@example.net', datetime.date(1922, 3, 3)],
 [1102792966, 'garciadennis@example.com', datetime.date(1934, 2, 12)],
 [1102792967, 'barbararobinson@example.net', datetime.date(1969, 10, 7)],
 [1102792968, 'blankenshipanthony@example.net', datetime.date(2006, 1, 28)],
 [1102792969, 'traci28@example.com', datetime.date(1925, 6, 21)],
 [1102792970, 'mosesmegan@example.net', datetime.date(1989, 6, 5)],
 [1102792971, 'llucas@example.org', datetime.date(1911, 1, 23)],
 [1102792972, 'marshallchad@example.com', datetime.date(1940, 4, 19)],
 [1102792973, 'terrylinda@example.net', datetime.date(1992, 5, 10)],
 [1102792974, 'patkins@example.com', datetime.date(1911, 1, 29)],
 [1102792975, 'kevinpruitt@example.org', datetime.date(1969, 6, 28)],
 [1102792976, 'kathy95@example.org', datetime.date(2017, 10, 21)],
 [1102792977, 'antonio29@example.org', datetime.date(2019, 12, 30)],
 [1102792978, 'fwright@example.net', datetime.date(1923, 11, 23)],
 [1102792979, 'travis15@example.org', datetime.date(1990, 3, 22)],
 [1102792980, 'ericsimmons@example.org', datetime.date(1966, 4, 1)],
 [1102792981, 'williamssean@example.net', datetime.date(1957, 2, 26)],
 [1102792982, 'parkerearl@example.com', datetime.date(1955, 7, 26)],
 [1102792983, 'meganfloyd@example.org', datetime.date(2023, 3, 31)],
 [1102792984, 'barnettjoseph@example.org', datetime.date(2014, 12, 10)],
 [1102792985, 'malik35@example.net', datetime.date(1919, 7, 21)],
 [1102792986, 'yward@example.org', datetime.date(1938, 8, 18)],
 [1102792987, 'jhart@example.com', datetime.date(1952, 2, 8)],
 [1102792988, 'nstewart@example.com', datetime.date(1978, 10, 6)],
 [1102792989, 'hunter76@example.net', datetime.date(1957, 12, 20)],
 [1102792990, 'diana54@example.com', datetime.date(2023, 4, 4)],
 [1102792991, 'scottbrowning@example.org', datetime.date(2016, 11, 24)],
 [1102792992, 'alexander18@example.net', datetime.date(1955, 5, 12)],
 [1102792993, 'benjamingonzalez@example.com', datetime.date(1912, 7, 13)],
 [1102792994, 'johnsonjenna@example.org', datetime.date(1977, 3, 1)],
 [1102792995, 'hshah@example.org', datetime.date(1956, 10, 29)],
 [1102792996, 'carterkevin@example.com', datetime.date(1979, 12, 28)],
 [1102792997, 'michaelbaker@example.net', datetime.date(1910, 9, 11)],
 [1102792998, 'phyllisayers@example.com', datetime.date(1964, 6, 7)],
 [1102792999, 'keithcarter@example.org', datetime.date(1934, 5, 13)],
 [1102793000, 'ibowen@example.net', datetime.date(2003, 3, 20)],
 [1102793001, 'ucruz@example.com', datetime.date(2001, 9, 21)],
 [1102793002, 'landerson@example.org', datetime.date(1941, 10, 16)],
 [1102793003, 'jesusbailey@example.net', datetime.date(1983, 8, 12)],
 [1102793004, 'vanessalarson@example.com', datetime.date(1975, 8, 5)],
 [1102793005, 'marc33@example.org', datetime.date(1965, 11, 24)],
 [1102793006, 'rroberts@example.org', datetime.date(1960, 8, 25)],
 [1102793007, 'wjackson@example.org', datetime.date(1934, 10, 18)],
 [1102793008, 'gfernandez@example.net', datetime.date(1942, 12, 31)],
 [1102793009, 'marcia02@example.com', datetime.date(1968, 2, 26)],
 [1102793010, 'kmedina@example.com', datetime.date(1937, 6, 8)],
 [1102793011, 'hwells@example.org', datetime.date(2010, 1, 12)],
 [1102793012, 'pfarrell@example.net', datetime.date(2002, 11, 24)],
 [1102793013, 'hollandrandy@example.org', datetime.date(2011, 7, 16)],
 [1102793014, 'zharrison@example.com', datetime.date(1965, 7, 2)],
 [1102793015, 'sowens@example.org', datetime.date(1988, 9, 15)],
 [1102793016, 'marysmith@example.net', datetime.date(1942, 1, 17)],
 [1102793017, 'wbrown@example.net', datetime.date(1977, 7, 20)],
 [1102793018, 'ramseytina@example.com', datetime.date(1935, 4, 16)],
 [1102793019, 'anthonydavid@example.com', datetime.date(1911, 2, 28)],
 [1102793020, 'xguzman@example.org', datetime.date(1998, 5, 3)],
 [1102793021, 'fisherscott@example.org', datetime.date(1977, 3, 1)],
 [1102793022, 'robinsonricky@example.net', datetime.date(1952, 6, 9)],
 [1102793023, 'cartervanessa@example.com', datetime.date(1998, 2, 18)],
 [1102793024, 'kimberly22@example.net', datetime.date(1925, 7, 12)],
 [1102793025, 'paula29@example.com', datetime.date(1967, 10, 17)],
 [1102793026, 'heather45@example.com', datetime.date(1957, 4, 23)],
 [1102793027, 'nrhodes@example.com', datetime.date(1927, 7, 6)],
 [1102793028, 'ashley55@example.org', datetime.date(2018, 11, 20)],
 [1102793029, 'janetfitzgerald@example.org', datetime.date(1920, 10, 19)],
 [1102793030, 'alanbowers@example.net', datetime.date(1979, 10, 3)],
 [1102793031, 'tylertran@example.org', datetime.date(1995, 1, 22)],
 [1102793032, 'julie19@example.com', datetime.date(1923, 3, 27)],
 [1102793033, 'stevenlong@example.net', datetime.date(1933, 7, 4)],
 [1102793034, 'connie98@example.com', datetime.date(1967, 5, 31)],
 [1102793035, 'websterjose@example.org', datetime.date(2006, 5, 19)],
 [1102793036, 'ccook@example.org', datetime.date(2003, 10, 26)],
 [1102793037, 'jessica72@example.com', datetime.date(2020, 10, 6)],
 [1102793038, 'davidperez@example.net', datetime.date(1953, 6, 4)],
 [1102793039, 'hartcaitlin@example.com', datetime.date(1965, 5, 20)],
 [1102793040, 'vgarcia@example.net', datetime.date(1944, 1, 26)],
 [1102793041, 'benjamingardner@example.org', datetime.date(1955, 8, 9)],
 [1102793042, 'kayla36@example.com', datetime.date(1962, 6, 13)],
 [1102793043, 'jamesfriedman@example.org', datetime.date(1963, 1, 25)],
 [1102793044, 'melissalam@example.com', datetime.date(1961, 2, 20)],
 [1102793045, 'anthony75@example.com', datetime.date(1977, 2, 10)],
 [1102793046, 'mtanner@example.com', datetime.date(1948, 8, 6)],
 [1102793047, 'ygarcia@example.com', datetime.date(1995, 7, 4)],
 [1102793048, 'kimberly66@example.org', datetime.date(1940, 4, 25)],
 [1102793049, 'lhouston@example.org', datetime.date(1965, 1, 29)],
 [1102793050, 'brandon03@example.org', datetime.date(2005, 8, 14)],
 [1102793051, 'fhines@example.org', datetime.date(2003, 5, 24)],
 [1102793052, 'brendabaker@example.com', datetime.date(1978, 2, 6)],
 [1102793053, 'wellsbrandon@example.com', datetime.date(1984, 9, 13)],
 [1102793054, 'davidnguyen@example.com', datetime.date(1963, 8, 12)],
 [1102793055, 'rebeccamaldonado@example.com', datetime.date(2008, 1, 13)],
 [1102793056, 'kristen85@example.net', datetime.date(1913, 8, 12)],
 [1102793057, 'shawntaylor@example.org', datetime.date(1920, 7, 26)],
 [1102793058, 'jmarshall@example.org', datetime.date(2023, 7, 25)],
 [1102793059, 'debrajackson@example.net', datetime.date(1968, 11, 2)],
 [1102793060, 'shannon87@example.net', datetime.date(1983, 4, 24)],
 [1102793061, 'carrillodustin@example.org', datetime.date(2019, 3, 8)],
 [1102793062, 'rponce@example.org', datetime.date(1939, 11, 27)],
 [1102793063, 'timothy86@example.org', datetime.date(2009, 2, 1)],
 [1102793064, 'andrewyoung@example.org', datetime.date(1980, 2, 14)],
 [1102793065, 'rangelscott@example.com', datetime.date(1931, 4, 13)],
 [1102793066, 'lucas31@example.org', datetime.date(1962, 7, 17)],
 [1102793067, 'vgreer@example.org', datetime.date(1990, 9, 20)],
 [1102793068, 'cwebster@example.net', datetime.date(1979, 8, 27)],
 [1102793069, 'zhowell@example.org', datetime.date(1989, 12, 6)],
 [1102793070, 'vazqueztiffany@example.org', datetime.date(1926, 4, 2)],
 [1102793071, 'nlewis@example.net', datetime.date(1910, 11, 18)],
 [1102793072, 'awatts@example.org', datetime.date(1988, 6, 26)],
 [1102793073, 'claire10@example.com', datetime.date(1978, 12, 14)],
 [1102793074, 'pwilson@example.org', datetime.date(1999, 2, 17)],
 [1102793075, 'danaclark@example.org', datetime.date(1927, 1, 20)],
 [1102793076, 'ogonzalez@example.org', datetime.date(1951, 9, 8)],
 [1102793077, 'christopher88@example.com', datetime.date(1988, 9, 29)],
 [1102793078, 'nturner@example.org', datetime.date(1927, 7, 17)],
 [1102793079, 'alvarezheather@example.net', datetime.date(1908, 11, 24)],
 [1102793080, 'dmann@example.org', datetime.date(1984, 2, 26)],
 [1102793081, 'benjamin67@example.com', datetime.date(2013, 2, 10)],
 [1102793082, 'michael32@example.net', datetime.date(1926, 12, 9)],
 [1102793083, 'griffithjoshua@example.com', datetime.date(1992, 8, 6)],
 [1102793084, 'ian64@example.org', datetime.date(1957, 10, 6)],
 [1102793085, 'bullockbrandon@example.org', datetime.date(2002, 9, 1)],
 [1102793086, 'karenhebert@example.org', datetime.date(1980, 2, 29)],
 [1102793087, 'fdavis@example.com', datetime.date(1975, 11, 25)],
 [1102793088, 'kelsey84@example.net', datetime.date(1914, 9, 28)],
 [1102793089, 'kirkbrett@example.com', datetime.date(2022, 5, 3)],
 [1102793090, 'herreraderrick@example.com', datetime.date(1925, 11, 7)],
 [1102793091, 'haleycampbell@example.org', datetime.date(1994, 12, 18)],
 [1102793092, 'john34@example.com', datetime.date(1980, 7, 12)],
 [1102793093, 'nhill@example.net', datetime.date(2016, 5, 15)],
 [1102793094, 'victoria94@example.org', datetime.date(2010, 6, 10)],
 [1102793095, 'dprince@example.com', datetime.date(1964, 7, 19)],
 [1102793096, 'qgillespie@example.net', datetime.date(2012, 2, 12)],
 [1102793097, 'jacqueline00@example.com', datetime.date(1961, 12, 5)],
 [1102793098, 'theresahunt@example.com', datetime.date(1979, 9, 30)],
 [1102793099, 'andersonalyssa@example.com', datetime.date(1940, 6, 29)],
 [1102793100, 'ewatkins@example.net', datetime.date(1984, 1, 16)],
 [1102793101, 'carrilloheather@example.com', datetime.date(1943, 2, 4)],
 [1102793102, 'whudson@example.net', datetime.date(1922, 5, 4)],
 [1102793103, 'joseph55@example.net', datetime.date(1958, 10, 17)],
 [1102793104, 'mcarrillo@example.org', datetime.date(1950, 7, 22)],
 [1102793105, 'glennsullivan@example.org', datetime.date(1909, 11, 2)],
 [1102793106, 'elizabethavery@example.net', datetime.date(1996, 10, 25)],
 [1102793107, 'jason60@example.com', datetime.date(2020, 1, 22)],
 [1102793108, 'elainesutton@example.net', datetime.date(1941, 7, 29)],
 [1102793109, 'carol93@example.com', datetime.date(1997, 4, 26)],
 [1102793110, 'carlapatterson@example.com', datetime.date(2013, 2, 14)],
 [1102793111, 'zachary61@example.com', datetime.date(1946, 5, 20)],
 [1102793112, 'joneselizabeth@example.com', datetime.date(1929, 1, 24)],
 [1102793113, 'victoriarojas@example.net', datetime.date(1957, 9, 19)],
 [1102793114, 'mlynch@example.com', datetime.date(1992, 1, 3)],
 [1102793115, 'eosborn@example.org', datetime.date(1976, 9, 11)],
 [1102793116, 'ejohnson@example.net', datetime.date(1914, 5, 6)],
 [1102793117, 'seangallagher@example.org', datetime.date(1991, 1, 8)],

In [9]:
data_parte2=pd.DataFrame(lista_conjunto_datos)
data_parte2.columns=columnas
rango=range(1,len(lista_conjunto_datos)+1)
data_parte2.index=rango
data_parte2

          Cédula         Correo electrónico Fecha de nacimiento
1     1102792827       thomas35@example.com          1979-10-19
2     1102792828   lopezmichael@example.com          2007-02-21
3     1102792829    parkerpeter@example.org          1971-10-27
4     1102792830     patricia76@example.net          2018-11-25
5     1102792831        unelson@example.com          1924-12-22
...          ...                        ...                 ...
996   1102793822    davismorgan@example.net          2002-08-31
997   1102793823      kharrison@example.com          1948-03-05
998   1102793824     jillhodges@example.net          1925-06-22
999   1102793825    elizabeth77@example.com          1955-08-12
1000  1102793826  douglasbaxter@example.org          2002-10-02

[1000 rows x 3 columns]

In [10]:
dataframe_unido=pd.merge(data_parte1,data_parte2, on='Cédula')
dataframe_unido.index=rango
dataframe_unido

,Cédula,Nombre,Apellido,Dirección,Correo electrónico,Fecha de nacimiento
1,1102792827,Rachel,Coleman,"5757 Thompson Overpass\nClarkmouth, FL 20893",thomas35@example.com,1979-10-19
2,1102792828,John,Burns,"404 Renee Wall Apt. 092\nNew Joshua, PA 85625",lopezmichael@example.com,2007-02-21
3,1102792829,Douglas,Ortega,"819 Ward Plains\nEast Monica, KY 81125",parkerpeter@example.org,1971-10-27
4,1102792830,Diana,Bradley,"0962 Amanda Crest\nSouth Abigail, VA 50910",patricia76@example.net,2018-11-25
5,1102792831,Chad,Atkins,"7960 Katherine Ferry Apt. 849\nLake Lisa, WY 1...",unelson@example.com,1924-12-22
...,...,...,...,...,...,...
996,1102793822,Steven,Logan,"79330 Thomas Knoll Suite 948\nTraviston, MA 71614",davismorgan@example.net,2002-08-31
997,1102793823,Marcia,Wells,38579 Nicholas Motorway Apt. 735\nLake Janiceb...,kharrison@example.com,1948-03-05
998,1102793824,John,Reilly,"4828 Coleman Lake Apt. 727\nCindyton, NY 58441",jillhodges@example.net,1925-06-22
999,1102793825,Kenneth,Roberts,"6532 Wood Junction\nNew Cindymouth, WY 53551",elizabeth77@example.com,1955-08-12
1000,1102793826,Ronnie,Schaefer,"7231 Miller Road\nPort William, AK 78565",douglasbaxter@example.org,2002-10-02

In [11]:
conexion.close()